# Generated by Django 6.0.2 on 2026-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old", models.IntegerField()),
                ("new", models.IntegerField()),
                ("changed", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
