# Generated by Django 6.0.2 on 2026-03-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_category_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["id"]},
        ),
    ]
